### ISSUE TITLE
About reproducibility

### ISSUE THREAD

**Issue by gouyt13** [IntelLabs/ScalableVectorSearch#35]
It seems that the MLVQ.py in _reproducibility/_ doesn't work properly due to the updated api. Could you please fix it?

**Comment by gouyt13** [comment]
I tried to fix it by replacing the str in LVQLoader by VectorDataLoader, but I met a new problem. 
`RuntimeError: Trying to deserialize incompatible object (two_level_lvq_dataset, v0.0.3) from file line 3`

**Comment by aguerreb** [comment]
Hi, and thanks for your interest in our work! The MLVQ.py script was created to reproduce some of the results in our [paper](https://arxiv.org/abs/2402.02044) on streaming similarity search, and uses auxiliary tools that have experimental support in the library so we do not guarantee compatibility with all SVS releases. Please let us know if you find this code useful and we’ll take this into account for future releases. In the meantime, you can run it without issues with [commit 6533a60](https://github.com/IntelLabs/ScalableVectorSearch/commit/6533a6056ff31597cf1b402928ab3e8941c32e3a). Hope this helps!
