### ISSUE TITLE
Populating the vector space with user data for testing

### ISSUE THREAD

**Issue by harievg** [IntelLabs/ScalableVectorSearch#40]
Hello,
Is it possible to populate the vector space with our own data for example our own text or pdf files and do the embeddings.
and query which is relevant for the our use case for testing.

if yes, what would be the possible way. or method in python to do so.

correct me if i am wrong:
i must use this python methods isn't:
```
# Build the index.
data = pysvs.read_vecs(os.path.join(test_data_dir, "data.fvecs"))
index = pysvs.Vamana.build(
    parameters,
    data,
    pysvs.DistanceType.L2,
    num_threads = 4,
)
```

if yes should we need to transform our docs to .fvecs file format. if yes is ther predefined pipelines for this.

thanks

**Comment by vyaivo** [comment]
Thank you for opening this issue. 
Yes, you would need to convert your vector embeddings to the `.fvecs` format. We will work on adding some examples to our documentation and let you know when that has been added.

**Comment by vyaivo** [comment]
To correct the record, you can *either* convert to `fvecs` or simply use numpy embeddings directly. This is now detailed in the documentation: https://intellabs.github.io/ScalableVectorSearch/howtos.html#how-to-prepare-your-own-vector-dataset
